spring:
  application:
    name: 'venda'
  datasource:
    username: root 
    password: 123456
    url: jdbc:mysql://localhost:3306/nfe
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8085
  servlet:
    context-path: /nfe
  